//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int idClient { get; set; }
        public Nullable<int> Dni { get; set; }
        public string NameCl { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string NameProv { get; set; }
        public string City { get; set; }
    }
}
